from __future__ import annotations

from dataclasses import dataclass
import os
import sys
import platform
import fnmatch
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime

APP_NAME = "DumpIt"
CONFIG_FILE_NAME = "dumpit.ini"

DEFAULT_INCLUDE = "*.al,app.json,*.gd,*.tscn,*.tres,*.cfg,*.ini,*.json,*.md,*.txt"
DEFAULT_EXCLUDE_DIRS = ".git,.vscode,.alpackages,bin,obj,node_modules,.idea,.vs,.devcontainer,.godot,.import"

SECTION_APP = "app"
PROFILE_PREFIX = "profile:"  # es: profile:Default
APP_BATCH_SELECTED_KEY = "batch_selected_profiles"  # csv list of profile names
DIFF_TEMP_HTML_PREFIX = "dumpit_diff_"
QUOTA_TEMP_HTML_PREFIX = "dumpit_quota_"
DIFF_TEMP_HTML_SUFFIX = ".html"
TIMESTAMP_FORMAT = "%Y-%m-%d_%H%M%S"
TIMESTAMP_STEM_RE = re.compile(r"^(?P<base>.+)_\d{4}-\d{2}-\d{2}_\d{6}$")
DEFAULT_TIMESTAMP_KEEP_OLD = "10"
DEFAULT_QUOTA_PATH_RULES = ""
QUOTA_TEST_DIR_NAMES = {"test", "tests", "__tests__", "spec", "specs"}


LIGHT_THEME_COLORS = {
    "bg": "#f0f0f0",
    "panel": "#f0f0f0",
    "panel_2": "#ffffff",
    "fg": "#000000",
    "muted": "#4b5563",
    "border": "#c9c9c9",
    "entry_bg": "#ffffff",
    "button_bg": "#f3f4f6",
    "button_active": "#e5e7eb",
    "tab_bg": "#e5e7eb",
    "accent": "#2563eb",
    "select_bg": "#2563eb",
    "select_fg": "#ffffff",
}

DARK_THEME_COLORS = {
    "bg": "#0f172a",
    "panel": "#111827",
    "panel_2": "#1f2937",
    "fg": "#e5e7eb",
    "muted": "#9ca3af",
    "border": "#374151",
    "entry_bg": "#020617",
    "button_bg": "#1f2937",
    "button_active": "#374151",
    "tab_bg": "#111827",
    "accent": "#3b82f6",
    "select_bg": "#2563eb",
    "select_fg": "#ffffff",
}

def get_default_project_dir() -> Path:
    # Se è un exe (PyInstaller), usa la cartella dell'exe; altrimenti cwd
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path.cwd()

def get_config_path() -> Path:
    system = platform.system().lower()
    if system.startswith("win"):
        base = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
        return Path(base) / APP_NAME / CONFIG_FILE_NAME
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) if xdg else (Path.home() / ".config")
    return base / APP_NAME / CONFIG_FILE_NAME

def ensure_parent_dir(p: Path) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)

def get_diff_temp_dir() -> Path:
    return Path(tempfile.gettempdir()) / APP_NAME

def cleanup_diff_temp_html_files() -> tuple[int, int]:
    """Delete temporary HTML files generated by the visual diff viewer.

    Returns:
        (deleted_count, failed_count)
    """
    temp_dir = get_diff_temp_dir()
    if not temp_dir.exists():
        return (0, 0)

    deleted = 0
    failed = 0
    for p in temp_dir.glob(f"{DIFF_TEMP_HTML_PREFIX}*{DIFF_TEMP_HTML_SUFFIX}"):
        try:
            if p.is_file():
                p.unlink()
                deleted += 1
        except Exception:
            failed += 1
    return deleted, failed

def cleanup_quota_temp_html_files() -> tuple[int, int]:
    """Delete temporary HTML files generated by Quota Inspector.

    Only files created by Open HTML report are removed. User-selected saved
    reports outside DumpIt's temp folder are not touched.
    """
    temp_dir = get_diff_temp_dir()
    if not temp_dir.exists():
        return (0, 0)

    deleted = 0
    failed = 0
    for p in temp_dir.glob(f"{QUOTA_TEMP_HTML_PREFIX}*{DIFF_TEMP_HTML_SUFFIX}"):
        try:
            if p.is_file():
                p.unlink()
                deleted += 1
        except Exception:
            failed += 1
    return deleted, failed

def is_os_dark_mode_enabled() -> bool:
    """Best-effort OS app theme detection.

    Windows: reads AppsUseLightTheme from the user theme registry key.
    macOS: reads AppleInterfaceStyle.
    Linux: checks common GTK/GNOME dark-theme hints.
    Unknown/unsupported systems default to light mode.
    """
    system = platform.system().lower()

    if system.startswith("win"):
        try:
            import winreg  # type: ignore

            key_path = r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key_path) as key:
                value, _type = winreg.QueryValueEx(key, "AppsUseLightTheme")
            return int(value) == 0
        except Exception:
            return False

    if system == "darwin":
        try:
            proc = subprocess.run(
                ["defaults", "read", "-g", "AppleInterfaceStyle"],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                timeout=2,
            )
            return "dark" in (proc.stdout or "").strip().lower()
        except Exception:
            return False

    # Linux / BSD best effort.
    for env_name in ("GTK_THEME", "QT_STYLE_OVERRIDE", "XDG_CURRENT_DESKTOP"):
        value = os.environ.get(env_name, "")
        if "dark" in value.lower():
            return True

    try:
        proc = subprocess.run(
            ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=2,
        )
        if "dark" in (proc.stdout or "").lower():
            return True
    except Exception:
        pass

    try:
        proc = subprocess.run(
            ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=2,
        )
        return "dark" in (proc.stdout or "").lower()
    except Exception:
        return False

def _normalize_patch_raw_path(raw: str) -> str:
    raw = (raw or "").strip()
    if not raw:
        return ""
    # Unified diff paths may be followed by timestamps separated by tabs/spaces.
    raw = raw.split("\t", 1)[0].strip()
    if raw.startswith('"') and raw.endswith('"'):
        raw = raw[1:-1]
    return raw.replace("\\", "/")

def _strip_patch_path(raw_path: str, strip_level: int) -> str | None:
    raw_path = _normalize_patch_raw_path(raw_path)
    if not raw_path or raw_path == "/dev/null":
        return None

    # Ignore absolute paths and drive-prefixed paths before stripping.
    if raw_path.startswith("/") or (len(raw_path) >= 3 and raw_path[1:3] == ":/"):
        return None

    parts = [part for part in raw_path.split("/") if part not in ("", ".")]
    if strip_level > 0:
        parts = parts[strip_level:]
    if not parts:
        return None
    if any(part == ".." for part in parts):
        return None
    return "/".join(parts)

def collect_unified_patch_target_paths(patch_path: Path, strip_level: int) -> set[str]:
    """Return target relative paths touched by a unified patch.

    This is intentionally conservative. It is used only for backup creation;
    git apply is still the source of truth for actual patch validation/application.
    """
    touched: set[str] = set()
    old_path: str | None = None

    for line in read_text_safely(patch_path).splitlines():
        if line.startswith("--- "):
            old_path = line[4:].strip()
            continue
        if line.startswith("+++ "):
            new_path = line[4:].strip()
            candidate = new_path if _normalize_patch_raw_path(new_path) != "/dev/null" else old_path
            rel = _strip_patch_path(candidate or "", strip_level)
            if rel:
                touched.add(rel)
            old_path = None

    return touched

def create_patch_backup(
    root: Path,
    patch_path: Path,
    strip_level: int,
    patch_directory: str | None = None,
) -> tuple[Path | None, int]:
    touched = {
        _prepend_patch_directory(rel, patch_directory)
        for rel in collect_unified_patch_target_paths(patch_path, strip_level)
    }
    existing = []
    for rel in sorted(touched, key=str.lower):
        src = root / Path(*rel.split("/"))
        try:
            if src.is_file():
                existing.append((rel, src))
        except OSError:
            pass

    if not existing:
        return None, 0

    backup_root = root / ".dumpit_patch_backup" / datetime.now().strftime("%Y%m%d_%H%M%S")
    for rel, src in existing:
        dst = backup_root / Path(*rel.split("/"))
        ensure_parent_dir(dst)
        shutil.copy2(src, dst)
    return backup_root, len(existing)

def _patch_rel_path(root: Path, rel_posix: str) -> Path:
    return root / Path(*rel_posix.split("/"))

def _normalize_patch_directory(patch_directory: str | None) -> str | None:
    if not patch_directory:
        return None
    normalized = patch_directory.replace("\\", "/").strip().strip("/")
    if not normalized or normalized == ".":
        return None
    parts = [part for part in normalized.split("/") if part not in ("", ".")]
    if any(part == ".." for part in parts):
        return None
    return "/".join(parts)

def _prepend_patch_directory(rel_posix: str, patch_directory: str | None) -> str:
    patch_directory = _normalize_patch_directory(patch_directory)
    if not patch_directory:
        return rel_posix
    return f"{patch_directory}/{rel_posix}"

def parse_csv_list(s: str) -> list[str]:
    return [x.strip() for x in s.split(",") if x.strip()]

def normalize_patterns(patterns: list[str]) -> list[str]:
    out: list[str] = []
    for p in patterns:
        p = p.strip()
        if not p:
            continue
        if p.startswith(".") and "*" not in p and "/" not in p and "\\" not in p:
            out.append(f"*{p.lower()}")
        else:
            out.append(p.lower())
    return out

def normalize_ui_path(p: str) -> str:
    """Normalize a path string for the current OS (fixes Tk forward slashes on Windows)."""
    p = (p or "").strip()
    if not p:
        return p
    return os.path.normpath(p)

def canon_path(p: Path) -> str:
    """Canonical path string for comparisons (case-insensitive on Windows)."""
    return os.path.normcase(os.path.normpath(str(p)))

def rel_posix(root: Path, file_path: Path) -> str:
    return file_path.relative_to(root).as_posix()

def should_skip_by_dir(rel_path: Path, exclude_dirs: set[str]) -> bool:
    return any(part.lower() in exclude_dirs for part in rel_path.parts)

def is_probably_binary(p: Path) -> bool:
    try:
        with p.open("rb") as f:
            chunk = f.read(8192)
        return b"\x00" in chunk
    except Exception:
        return True

def read_text_safely(p: Path) -> str:
    for enc in ("utf-8-sig", "utf-8"):
        try:
            return p.read_text(encoding=enc)
        except UnicodeDecodeError:
            pass
    return p.read_text(encoding="utf-8", errors="replace")

def matches_any(rel_path_posix: str, name: str, patterns: list[str]) -> bool:
    rp = rel_path_posix.lower()
    nm = name.lower()
    for pat in patterns:
        if ("/" in pat) or ("\\" in pat):
            if fnmatch.fnmatch(rp, pat.replace("\\", "/")):
                return True
        else:
            if fnmatch.fnmatch(nm, pat):
                return True
    return False

def strip_output_timestamp_from_stem(stem: str) -> str:
    match = TIMESTAMP_STEM_RE.match(stem or "")
    if match:
        return match.group("base")
    return stem

def build_default_output(root: Path, add_ts: bool = False) -> Path:
    path = root / f"{root.name}.txt"
    if add_ts:
        return add_timestamp_to_output_path(path)
    return path

def get_output_base_path(path: Path) -> Path:
    stem = strip_output_timestamp_from_stem(path.stem)
    return path.with_name(f"{stem}{path.suffix}")

def add_timestamp_to_output_path(path: Path, now: datetime | None = None) -> Path:
    base = get_output_base_path(path)
    ts = (now or datetime.now()).strftime(TIMESTAMP_FORMAT)
    return base.with_name(f"{base.stem}_{ts}{base.suffix}")

def resolve_export_output_path(root: Path, raw_output_file: str, add_timestamp: bool) -> Path:
    raw_output_file = normalize_ui_path(raw_output_file or "")
    base_path = Path(raw_output_file).resolve() if raw_output_file else build_default_output(root, False)
    if add_timestamp:
        return add_timestamp_to_output_path(base_path)
    return base_path

def timestamped_output_regex(base_path: Path) -> re.Pattern[str]:
    base = get_output_base_path(base_path)
    return re.compile(
        r"^"
        + re.escape(base.stem)
        + r"_(?P<ts>\d{4}-\d{2}-\d{2}_\d{6})"
        + re.escape(base.suffix)
        + r"$"
    )

def collect_timestamped_output_files(path: Path) -> list[Path]:
    base = get_output_base_path(path)
    regex = timestamped_output_regex(base)
    try:
        children = list(base.parent.iterdir())
    except OSError:
        return []

    files: list[Path] = []
    for child in children:
        try:
            if child.is_file() and regex.match(child.name):
                files.append(child)
        except OSError:
            continue
    return files

def build_output_exclude_files(out_path: Path, add_timestamp: bool) -> set[str]:
    exclude_files = {canon_path(out_path)}
    if add_timestamp:
        base = get_output_base_path(out_path)
        exclude_files.add(canon_path(base))
        exclude_files.update(canon_path(path) for path in collect_timestamped_output_files(base))
    return exclude_files

def parse_timestamp_keep_old_value(raw: str, default: str = DEFAULT_TIMESTAMP_KEEP_OLD) -> int:
    value = (raw or "").strip()
    if not value:
        value = default
    try:
        parsed = int(value)
    except ValueError:
        raise ValueError("Max old timestamped exports to keep must be an integer.") from None
    if parsed < 0:
        raise ValueError("Max old timestamped exports to keep must be 0 or greater.")
    return parsed

def cleanup_old_timestamped_outputs(out_path: Path, keep_old_count: int) -> tuple[int, int]:
    keep_old_count = max(0, int(keep_old_count))
    regex = timestamped_output_regex(out_path)
    candidates: list[tuple[str, int, Path]] = []

    for path in collect_timestamped_output_files(out_path):
        match = regex.match(path.name)
        if not match:
            continue
        try:
            mtime_ns = path.stat().st_mtime_ns
        except OSError:
            mtime_ns = 0
        candidates.append((match.group("ts"), mtime_ns, path))

    # Keep the newest export plus N older timestamped exports.
    candidates.sort(key=lambda item: (item[0], item[1], item[2].name.lower()), reverse=True)
    keep_total = keep_old_count + 1
    deleted = 0
    failed = 0
    for _ts, _mtime_ns, path in candidates[keep_total:]:
        try:
            path.unlink()
            deleted += 1
        except OSError:
            failed += 1
    return deleted, failed

@dataclass(slots=True)
class ExportFileEntry:
    path: Path
    rel_path: str
    header_path: str
    text: str
    line_count: int
    modified_at: str

@dataclass(slots=True)
class DumpSnapshot:
    source: Path
    files: dict[str, str]

@dataclass(slots=True, frozen=True)
class DumpImportEntry:
    source_header_path: str
    rel_path: str
    target_path: Path
    text: str
    exists: bool
    action: str

@dataclass(slots=True, frozen=True)
class DumpImportSkippedEntry:
    source_header_path: str
    reason: str

@dataclass(slots=True)
class DumpImportPlan:
    dump_path: Path
    target_root: Path
    source_root: str
    entries: tuple[DumpImportEntry, ...]
    skipped: tuple[DumpImportSkippedEntry, ...]

    @property
    def create_count(self) -> int:
        return sum(1 for entry in self.entries if entry.action == "create")

    @property
    def overwrite_count(self) -> int:
        return sum(1 for entry in self.entries if entry.action == "overwrite")

    @property
    def skip_existing_count(self) -> int:
        return sum(1 for entry in self.entries if entry.action == "skip_existing")

    @property
    def write_count(self) -> int:
        return self.create_count + self.overwrite_count

    @property
    def total_count(self) -> int:
        return len(self.entries) + len(self.skipped)

@dataclass(slots=True, frozen=True)
class DumpImportResult:
    created: int
    overwritten: int
    skipped_existing: int
    skipped_invalid: int
    backed_up: int
    backup_root: Path | None

    @property
    def written(self) -> int:
        return int(self.created) + int(self.overwritten)

@dataclass(slots=True)
class DumpDiffResult:
    old: DumpSnapshot
    new: DumpSnapshot
    added: list[str]
    removed: list[str]
    modified: list[str]
    unchanged: list[str]

    @property
    def changed_count(self) -> int:
        return len(self.added) + len(self.removed) + len(self.modified)
